############################################################################
############################### 17/Jul/93 ##################################
############################   Version 1.0   ###############################
######################### Author: Paolo Cignoni ############################
#									   #
#  FILE:	Makefile						   #
#									   #
#  PURPOSE:	Generating InCoDe program				   #
#									   #
#    NOTES:	The two triangulators share a part of code. Such part of   #
#		code, contained in directory OList, concerns management	   #
#		of list, error message functions and machine indipendent   #
#		timing functions.					   #
#	        Note that this code require an ANSI C compiler.		   #
#									   #
############################################################################
############################################################################


BENCHMARK_NAME = dt
SOURCES_C = main.c error.c ggveclib.c geometry.c list.c unifgrid.c file.c stat.c

include ../Makefile.common
